// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMD.Models;

#nullable disable

namespace TMD.Migrations
{
    [DbContext(typeof(TmdContext))]
    [Migration("20251127072335_CreateChat")]
    partial class CreateChat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMD.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<decimal?>("ActualWorkHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("ApprovedOvertimeHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("CheckInAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CheckInFiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckInIpaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CheckInIPAddress");

                    b.Property<decimal?>("CheckInLatitude")
                        .HasColumnType("decimal(10, 8)");

                    b.Property<decimal?>("CheckInLongitude")
                        .HasColumnType("decimal(11, 8)");

                    b.Property<string>("CheckInNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CheckInPhotos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckOutAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CheckOutFiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckOutIpaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CheckOutIPAddress");

                    b.Property<decimal?>("CheckOutLatitude")
                        .HasColumnType("decimal(10, 8)");

                    b.Property<decimal?>("CheckOutLongitude")
                        .HasColumnType("decimal(11, 8)");

                    b.Property<string>("CheckOutNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CheckOutPhotos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("DeductionAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DeductionHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool>("HasLateRequest")
                        .HasColumnType("bit");

                    b.Property<bool>("HasOvertimeRequest")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOvertimeApproved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsWithinGeofence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("LateRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("OvertimeRequestId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SalaryMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(1.0m);

                    b.Property<int?>("ScheduleExceptionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("StandardWorkHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(8m);

                    b.Property<decimal?>("TotalHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__8B69261CEBF9F49E");

                    b.HasIndex("LateRequestId");

                    b.HasIndex("OvertimeRequestId");

                    b.HasIndex("ScheduleExceptionId");

                    b.HasIndex(new[] { "UserId", "WorkDate" }, "IX_Attendances_UserId_WorkDate");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("TMD.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId")
                        .HasName("PK__AuditLog__EB5F6CBD62F10178");

                    b.HasIndex(new[] { "UserId", "Timestamp" }, "IX_AuditLogs_UserId_Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TMD.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MessageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("TMD.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BED40AFE942");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TMD.Models.LateRequest", b =>
                {
                    b.Property<int>("LateRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LateRequestId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeOnly>("ExpectedArrivalTime")
                        .HasColumnType("time");

                    b.Property<string>("ProofDocument")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("RequestDate")
                        .HasColumnType("date");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LateRequestId")
                        .HasName("PK__LateRequ__6814EE075B2D35BA");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex(new[] { "Status" }, "IX_LateRequests_Status");

                    b.HasIndex(new[] { "UserId", "RequestDate" }, "IX_LateRequests_UserId_RequestDate");

                    b.ToTable("LateRequests");
                });

            modelBuilder.Entity("TMD.Models.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveRequestId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProofDocument")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LeaveRequestId")
                        .HasName("PK__LeaveReq__609421EE09998BE8");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex(new[] { "StartDate" }, "IX_LeaveRequests_StartDate");

                    b.HasIndex(new[] { "UserId", "Status" }, "IX_LeaveRequests_UserId_Status");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("TMD.Models.LoginHistory", b =>
                {
                    b.Property<int>("LoginHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginHistoryId"));

                    b.Property<string>("Browser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Device")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FailReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<bool?>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LoginHistoryId")
                        .HasName("PK__LoginHis__2773EA9F24699591");

                    b.HasIndex(new[] { "UserId" }, "IX_LoginHistory_UserId");

                    b.ToTable("LoginHistory", (string)null);
                });

            modelBuilder.Entity("TMD.Models.OvertimeRequest", b =>
                {
                    b.Property<int>("OvertimeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OvertimeRequestId"));

                    b.Property<DateTime>("ActualCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsExpired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TaskDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("OvertimeRequestId")
                        .HasName("PK__Overtime__F97D0DCA560E4C6E");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex(new[] { "ExpiryDate" }, "IX_OvertimeRequests_ExpiryDate");

                    b.HasIndex(new[] { "IsExpired", "Status" }, "IX_OvertimeRequests_IsExpired_Status");

                    b.HasIndex(new[] { "UserId", "WorkDate" }, "IX_OvertimeRequests_UserId_WorkDate");

                    b.ToTable("OvertimeRequests");
                });

            modelBuilder.Entity("TMD.Models.PasswordResetHistory", b =>
                {
                    b.Property<int>("ResetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResetId"));

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("OldPasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ResetByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResetReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResetTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ResetId")
                        .HasName("PK__Password__783CF04DF61E0EB7");

                    b.HasIndex("ResetByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetHistory", (string)null);
                });

            modelBuilder.Entity("TMD.Models.PasswordResetOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Password__3214EC07F3B72DCD");

                    b.HasIndex(new[] { "Email" }, "IX_PasswordResetOTPs_Email");

                    b.HasIndex(new[] { "OtpCode" }, "IX_PasswordResetOTPs_OtpCode");

                    b.HasIndex(new[] { "UserId" }, "IX_PasswordResetOTPs_UserId");

                    b.ToTable("PasswordResetOTPs", (string)null);
                });

            modelBuilder.Entity("TMD.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ResendAvailableAt")
                        .HasColumnType("datetime");

                    b.Property<string>("TokenCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Password__3214EC071B5D66E3");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetToken", (string)null);
                });

            modelBuilder.Entity("TMD.Models.PasswordResetToken1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Password__3214EC071EAAF641");

                    b.HasIndex(new[] { "Token" }, "IX_PasswordResetTokens_Token");

                    b.HasIndex(new[] { "UserId" }, "IX_PasswordResetTokens_UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("TMD.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A31ADBDE1");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160E7BCAB19")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TMD.Models.SalaryAdjustment", b =>
                {
                    b.Property<int>("AdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdjustmentId"));

                    b.Property<DateTime?>("AdjustedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("AdjustedBy")
                        .HasColumnType("int");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int?>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Hours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("AdjustmentId")
                        .HasName("PK__SalaryAd__E60DB893E5A43735");

                    b.HasIndex("AdjustedBy");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("AttendanceId");

                    b.HasIndex(new[] { "AdjustmentType" }, "IX_SalaryAdjustments_AdjustmentType");

                    b.HasIndex(new[] { "UserId", "WorkDate" }, "IX_SalaryAdjustments_UserId_WorkDate");

                    b.ToTable("SalaryAdjustments");
                });

            modelBuilder.Entity("TMD.Models.SalaryConfigCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId")
                        .HasName("PK__SalaryCo__19093A0BE0B88366");

                    b.HasIndex(new[] { "CategoryCode" }, "UQ__SalaryCo__371BA955E866D9B3")
                        .IsUnique();

                    b.ToTable("SalaryConfigCategories");
                });

            modelBuilder.Entity("TMD.Models.SalaryConfigHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime?>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<int>("ConfigId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("HistoryId")
                        .HasName("PK__SalaryCo__4D7B4ABDBEE5882D");

                    b.HasIndex(new[] { "ChangedBy" }, "IX_SalaryConfigHistory_ChangedBy");

                    b.HasIndex(new[] { "ConfigId" }, "IX_SalaryConfigHistory_ConfigId");

                    b.ToTable("SalaryConfigHistory", (string)null);
                });

            modelBuilder.Entity("TMD.Models.SalaryConfiguration", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ConfigCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsEditable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConfigId")
                        .HasName("PK__SalaryCo__C3BC335CE83B99FF");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "CategoryId" }, "IX_SalaryConfigurations_CategoryId");

                    b.HasIndex(new[] { "IsActive" }, "IX_SalaryConfigurations_IsActive");

                    b.HasIndex(new[] { "ConfigCode" }, "UQ__SalaryCo__5488CE6808AA130F")
                        .IsUnique();

                    b.ToTable("SalaryConfigurations");
                });

            modelBuilder.Entity("TMD.Models.SystemSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("ApplyMethod")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Add");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("SettingId")
                        .HasName("PK__SystemSe__54372B1DEA688F4D");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "Category" }, "IX_SystemSettings_Category");

                    b.HasIndex(new[] { "Category", "ApplyMethod" }, "IX_SystemSettings_Category_ApplyMethod")
                        .HasFilter("([IsActive]=(1))");

                    b.HasIndex(new[] { "IsActive" }, "IX_SystemSettings_IsActive");

                    b.HasIndex(new[] { "IsEnabled" }, "IX_SystemSettings_IsEnabled");

                    b.HasIndex(new[] { "Priority" }, "IX_SystemSettings_Priority")
                        .IsDescending()
                        .HasFilter("([IsActive]=(1) AND [IsEnabled]=(1))");

                    b.HasIndex(new[] { "SettingKey" }, "UQ__SystemSe__01E719AD7D8ED9CB")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("TMD.Models.SystemSettingsBackup20251123", b =>
                {
                    b.Property<string>("ApplyMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("bit");

                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.ToTable("SystemSettings_Backup_20251123", (string)null);
                });

            modelBuilder.Entity("TMD.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Platform")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Medium");

                    b.Property<int?>("TargetPerWeek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("TaskId")
                        .HasName("PK__Tasks__7C6949B188536639");

                    b.HasIndex(new[] { "Deadline" }, "IX_Tasks_Deadline")
                        .HasFilter("([Deadline] IS NOT NULL)");

                    b.HasIndex(new[] { "IsActive", "Deadline" }, "IX_Tasks_IsActive_Deadline")
                        .HasFilter("([Deadline] IS NOT NULL)");

                    b.HasIndex(new[] { "Priority" }, "IX_Tasks_Priority");

                    b.HasIndex(new[] { "UpdatedAt" }, "IX_Tasks_UpdatedAt");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TMD.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CB231ECDE");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_Users_DepartmentId");

                    b.HasIndex(new[] { "RoleId" }, "IX_Users_RoleId");

                    b.HasIndex(new[] { "Username" }, "IX_Users_Username");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4FED6441B")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TMD.Models.UserSalarySetting", b =>
                {
                    b.Property<int>("UserSalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSalaryId"));

                    b.Property<decimal?>("AllowanceAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("BaseSalary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(5000000m);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("DefaultOvertimeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(1.5m);

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SalaryType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Monthly");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserSalaryId")
                        .HasName("PK__UserSala__528D2F424FA45E81");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "UserId" }, "UQ__UserSala__1788CC4D6A1C46E6")
                        .IsUnique();

                    b.ToTable("UserSalarySettings");
                });

            modelBuilder.Entity("TMD.Models.UserTask", b =>
                {
                    b.Property<int>("UserTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTaskId"));

                    b.Property<int?>("CompletedThisWeek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ReportLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("TODO");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("UserTaskId")
                        .HasName("PK__UserTask__4EF5961FD9ECDA05");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Status" }, "IX_UserTasks_Status");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("TMD.Models.VwActiveSalarySetting", b =>
                {
                    b.Property<string>("ApplyMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ActiveSalarySettings", (string)null);
                });

            modelBuilder.Entity("TMD.Models.VwPendingRequestsSummary", b =>
                {
                    b.Property<int?>("PendingCount")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.ToTable((string)null);

                    b.ToView("vw_PendingRequestsSummary", (string)null);
                });

            modelBuilder.Entity("TMD.Models.VwSalaryCalculation", b =>
                {
                    b.Property<decimal?>("AutoDeduction")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("BaseSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("DailySalaryTotal")
                        .HasColumnType("numeric(38, 8)");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LateDays")
                        .HasColumnType("int");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<decimal?>("MonthlyAllowance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("OvertimeSalary")
                        .HasColumnType("numeric(38, 12)");

                    b.Property<string>("SalaryType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TotalOvertimeHours")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("TotalWorkHours")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkedDays")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_SalaryCalculation", (string)null);
                });

            modelBuilder.Entity("TMD.Models.VwTaskPerformance", b =>
                {
                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CompletedThisWeek")
                        .HasColumnType("int");

                    b.Property<double?>("CompletionPercentage")
                        .HasColumnType("float");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Platform")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReportLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TargetPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_TaskPerformance", (string)null);
                });

            modelBuilder.Entity("TMD.Models.VwTasksWithDeadline", b =>
                {
                    b.Property<int?>("AssignedUserCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DaysUntilDeadline")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeadlineStatus")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Platform")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TargetPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ToTable((string)null);

                    b.ToView("vw_TasksWithDeadline", (string)null);
                });

            modelBuilder.Entity("TMD.Models.VwTodayAttendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CheckInAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckOutAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsLate")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TotalHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_TodayAttendance", (string)null);
                });

            modelBuilder.Entity("TMD.Models.VwUserDetail", b =>
                {
                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable((string)null);

                    b.ToView("vw_UserDetails", (string)null);
                });

            modelBuilder.Entity("TMD.Models.WorkScheduleException", b =>
                {
                    b.Property<int>("ExceptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExceptionId"));

                    b.Property<TimeOnly?>("CheckInStandardTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("CheckInStartTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("CheckOutMinTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExceptionType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Normal");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("OvertimeMultiplier")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("SalaryMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(1.0m);

                    b.Property<decimal?>("StandardHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("ExceptionId")
                        .HasName("PK__WorkSche__26981D8847CF3126");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "UserId" }, "IX_WorkScheduleExceptions_UserId");

                    b.HasIndex(new[] { "WorkDate" }, "IX_WorkScheduleExceptions_WorkDate");

                    b.ToTable("WorkScheduleExceptions");
                });

            modelBuilder.Entity("TMD.Models.Attendance", b =>
                {
                    b.HasOne("TMD.Models.LateRequest", "LateRequest")
                        .WithMany("Attendances")
                        .HasForeignKey("LateRequestId")
                        .HasConstraintName("FK_Attendances_LateRequest");

                    b.HasOne("TMD.Models.OvertimeRequest", "OvertimeRequest")
                        .WithMany("Attendances")
                        .HasForeignKey("OvertimeRequestId")
                        .HasConstraintName("FK_Attendances_OvertimeRequest");

                    b.HasOne("TMD.Models.WorkScheduleException", "ScheduleException")
                        .WithMany("Attendances")
                        .HasForeignKey("ScheduleExceptionId")
                        .HasConstraintName("FK_Attendances_ScheduleException");

                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Attendanc__UserI__534D60F1");

                    b.Navigation("LateRequest");

                    b.Navigation("OvertimeRequest");

                    b.Navigation("ScheduleException");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.AuditLog", b =>
                {
                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__AuditLogs__UserI__571DF1D5");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.LateRequest", b =>
                {
                    b.HasOne("TMD.Models.User", "ReviewedByNavigation")
                        .WithMany("LateRequestReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("FK_LateRequests_Reviewer");

                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("LateRequestUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LateRequests_User");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.LeaveRequest", b =>
                {
                    b.HasOne("TMD.Models.User", "ReviewedByNavigation")
                        .WithMany("LeaveRequestReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("FK_LeaveRequests_Reviewer");

                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("LeaveRequestUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LeaveRequests_User");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.LoginHistory", b =>
                {
                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__LoginHist__UserI__5BE2A6F2");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.OvertimeRequest", b =>
                {
                    b.HasOne("TMD.Models.User", "ReviewedByNavigation")
                        .WithMany("OvertimeRequestReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("FK_OvertimeRequests_Reviewer");

                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("OvertimeRequestUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OvertimeRequests_User");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.PasswordResetHistory", b =>
                {
                    b.HasOne("TMD.Models.User", "ResetByUser")
                        .WithMany("PasswordResetHistoryResetByUsers")
                        .HasForeignKey("ResetByUserId")
                        .HasConstraintName("FK__PasswordR__Reset__60A75C0F");

                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("PasswordResetHistoryUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PasswordR__UserI__5FB337D6");

                    b.Navigation("ResetByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.PasswordResetOtp", b =>
                {
                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("PasswordResetOtps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PasswordResetOTPs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.PasswordResetToken", b =>
                {
                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PasswordResetToken_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.PasswordResetToken1", b =>
                {
                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("PasswordResetToken1s")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PasswordResetTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.SalaryAdjustment", b =>
                {
                    b.HasOne("TMD.Models.User", "AdjustedByNavigation")
                        .WithMany("SalaryAdjustmentAdjustedByNavigations")
                        .HasForeignKey("AdjustedBy")
                        .IsRequired()
                        .HasConstraintName("FK__SalaryAdj__Adjus__42E1EEFE");

                    b.HasOne("TMD.Models.User", "ApprovedByNavigation")
                        .WithMany("SalaryAdjustmentApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__SalaryAdj__Appro__43D61337");

                    b.HasOne("TMD.Models.Attendance", "Attendance")
                        .WithMany("SalaryAdjustments")
                        .HasForeignKey("AttendanceId")
                        .HasConstraintName("FK__SalaryAdj__Atten__41EDCAC5");

                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("SalaryAdjustmentUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SalaryAdj__UserI__40F9A68C");

                    b.Navigation("AdjustedByNavigation");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Attendance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.SalaryConfigHistory", b =>
                {
                    b.HasOne("TMD.Models.User", "ChangedByNavigation")
                        .WithMany("SalaryConfigHistories")
                        .HasForeignKey("ChangedBy")
                        .IsRequired()
                        .HasConstraintName("FK__SalaryCon__Chang__6BE40491");

                    b.HasOne("TMD.Models.SalaryConfiguration", "Config")
                        .WithMany("SalaryConfigHistories")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SalaryCon__Confi__6AEFE058");

                    b.Navigation("ChangedByNavigation");

                    b.Navigation("Config");
                });

            modelBuilder.Entity("TMD.Models.SalaryConfiguration", b =>
                {
                    b.HasOne("TMD.Models.SalaryConfigCategory", "Category")
                        .WithMany("SalaryConfigurations")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__SalaryCon__Categ__681373AD");

                    b.HasOne("TMD.Models.User", "CreatedByNavigation")
                        .WithMany("SalaryConfigurationCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__SalaryCon__Creat__690797E6");

                    b.HasOne("TMD.Models.User", "UpdatedByNavigation")
                        .WithMany("SalaryConfigurationUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__SalaryCon__Updat__69FBBC1F");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("TMD.Models.SystemSetting", b =>
                {
                    b.HasOne("TMD.Models.User", "UpdatedByNavigation")
                        .WithMany("SystemSettings")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__SystemSet__Updat__0A9D95DB");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("TMD.Models.User", b =>
                {
                    b.HasOne("TMD.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Users__Departmen__4222D4EF");

                    b.HasOne("TMD.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__RoleId__4316F928");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TMD.Models.UserSalarySetting", b =>
                {
                    b.HasOne("TMD.Models.User", "CreatedByNavigation")
                        .WithMany("UserSalarySettingCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__UserSalar__Creat__30C33EC3");

                    b.HasOne("TMD.Models.User", "UpdatedByNavigation")
                        .WithMany("UserSalarySettingUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK__UserSalar__Updat__31B762FC");

                    b.HasOne("TMD.Models.User", "User")
                        .WithOne("UserSalarySettingUser")
                        .HasForeignKey("TMD.Models.UserSalarySetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserSalar__UserI__2FCF1A8A");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.UserTask", b =>
                {
                    b.HasOne("TMD.Models.Task", "Task")
                        .WithMany("UserTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserTasks__TaskI__4D94879B");

                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("UserTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserTasks__UserI__4CA06362");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.WorkScheduleException", b =>
                {
                    b.HasOne("TMD.Models.User", "CreatedByNavigation")
                        .WithMany("WorkScheduleExceptionCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__WorkSched__Creat__3A4CA8FD");

                    b.HasOne("TMD.Models.Department", "Department")
                        .WithMany("WorkScheduleExceptions")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__WorkSched__Depar__395884C4");

                    b.HasOne("TMD.Models.User", "User")
                        .WithMany("WorkScheduleExceptionUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__WorkSched__UserI__3864608B");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMD.Models.Attendance", b =>
                {
                    b.Navigation("SalaryAdjustments");
                });

            modelBuilder.Entity("TMD.Models.Department", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("WorkScheduleExceptions");
                });

            modelBuilder.Entity("TMD.Models.LateRequest", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("TMD.Models.OvertimeRequest", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("TMD.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TMD.Models.SalaryConfigCategory", b =>
                {
                    b.Navigation("SalaryConfigurations");
                });

            modelBuilder.Entity("TMD.Models.SalaryConfiguration", b =>
                {
                    b.Navigation("SalaryConfigHistories");
                });

            modelBuilder.Entity("TMD.Models.Task", b =>
                {
                    b.Navigation("UserTasks");
                });

            modelBuilder.Entity("TMD.Models.User", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("AuditLogs");

                    b.Navigation("LateRequestReviewedByNavigations");

                    b.Navigation("LateRequestUsers");

                    b.Navigation("LeaveRequestReviewedByNavigations");

                    b.Navigation("LeaveRequestUsers");

                    b.Navigation("LoginHistories");

                    b.Navigation("OvertimeRequestReviewedByNavigations");

                    b.Navigation("OvertimeRequestUsers");

                    b.Navigation("PasswordResetHistoryResetByUsers");

                    b.Navigation("PasswordResetHistoryUsers");

                    b.Navigation("PasswordResetOtps");

                    b.Navigation("PasswordResetToken1s");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("SalaryAdjustmentAdjustedByNavigations");

                    b.Navigation("SalaryAdjustmentApprovedByNavigations");

                    b.Navigation("SalaryAdjustmentUsers");

                    b.Navigation("SalaryConfigHistories");

                    b.Navigation("SalaryConfigurationCreatedByNavigations");

                    b.Navigation("SalaryConfigurationUpdatedByNavigations");

                    b.Navigation("SystemSettings");

                    b.Navigation("UserSalarySettingCreatedByNavigations");

                    b.Navigation("UserSalarySettingUpdatedByNavigations");

                    b.Navigation("UserSalarySettingUser");

                    b.Navigation("UserTasks");

                    b.Navigation("WorkScheduleExceptionCreatedByNavigations");

                    b.Navigation("WorkScheduleExceptionUsers");
                });

            modelBuilder.Entity("TMD.Models.WorkScheduleException", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
